name: Dependency Submission

on:
  workflow_dispatch:

permissions: 
  contents: read

jobs:
  dependency-submission:
    permissions: 
      id-token: write
      contents: write
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
        node-version: [ '24.x' ]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build Components
        run: |
              npm i
              npx lerna run build --stream
              powershell ./build/dotnet-restore.ps1
              powershell ./build/dotnet-build.ps1
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@d433c2f467e149a8009c8fbce92cc708ed15ef7b # v0.1.0
        with:
          detectorsFilter: "NuGetProjectCentric,Npm,NpmLockfile3"
